<?php

require 'vendor/autoload.php';

date_default_timezone_set('Asia/Shanghai');

$httpClient = new \GuzzleHttp\Client();

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://b2c.csair.com/ita/intl/app');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "language=zh&country=cn&m=1&adt=2&cnn=1&inf=0&dep=PEK&depName=PEK&arr=PQC&arrName=PQC&date=20200124&dep=PQC&depName=PQC&arr=PEK&arrName=PEK&date=20200130&flexible=1");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$responseHtml = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

preg_match("/execution=(\w+)/", $responseHtml, $matches);
if (empty($matches)) {
	echo ">> get ticket filed" . PHP_EOL;
	var_dump($responseHtml);
	return;
}

$ticket = $matches[1];
// $ticket = "38834f361032ab47db22cfc3aa9c3ba5";
echo sprintf('>> ticket = %s', $ticket) . PHP_EOL;

echo ">> get price" . PHP_EOL;
$url = "https://b2c.csair.com/ita/rest/intl/shop/calendar?execution=$ticket";

$response = (string)$httpClient->request("GET", $url)->getBody();

$result = json_decode($response, true);

$fileName = __DIR__ . "/result.csv";
$fp = fopen($fileName, "a");

$prices = [];
$time = date('Y-m-d H:i:s');
$rows = $result["ita"]["calendar"]['day'] ?? [];
if (empty($rows)) {
	echo "!! invalid response $response" . PHP_EOL;
	return;
}
echo ">> extract price and write to file" . PHP_EOL;
foreach($rows as $row) {
	$date = $row['date'];
	$price = $row['solution']['displayTotal']['amount'];
	$prices[$date] = $price;
}
fputcsv($fp, array_merge([$time], array_values($prices)));

fclose($fp);